# Generated by Django 5.2.3 on 2026-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_type', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField()),
                ('status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'expires_at'], name='users_idemp_key_a32466_idx')],
            },
        ),
    ]
