# Generated by Django 5.2.3 on 2026-05-20 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_idempotencykey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='users_leave_employe_1e4dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['requested_at'], name='users_leave_request_64147f_idx'),
        ),
    ]
