# Generated by Django 5.2.3 on 2026-05-31 19:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_leave_users_leave_employe_1e4dbc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, help_text='Unique company identifier', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.BinaryField(blank=True, help_text='Stored face encoding for verification', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of fingerprint data', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reset_token_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of reset token', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action', '-created_at'], name='users_activ_user_id_d57a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='users_activ_created_31380b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='users_compa_status_448544_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_code'], name='users_compa_company_b9bf50_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='users_compa_name_8c4c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'name'], name='users_depar_company_a1c6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='users_emplo_email_e2f2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='users_emplo_phone_3f963a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'status'], name='users_emplo_company_141c02_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'company'], name='users_emplo_user_id_b12ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['-created_at'], name='users_emplo_created_8e92cf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['reset_token_hash', 'reset_token_expires'], name='users_emplo_reset_t_4227d8_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['user_id', 'created_at'], name='users_idemp_user_id_227bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token', 'expires_at'], name='users_passw_token_adc7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'is_used'], name='users_passw_user_id_5ee9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'status'], name='users_profi_role_f62e36_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['company', 'role'], name='users_profi_company_5752ec_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'role'], name='users_profi_user_id_0b4ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company', 'is_active'], name='users_shift_company_05c38c_idx'),
        ),
    ]
