# Generated by Django 5.2.3 on 2026-06-11 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_employee_reset_token_company_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='beacon_grace_period',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='lunch_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lunch_end',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lunch_start',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='office_beacon_uuids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_max_interval',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_min_interval',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_window',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('face_fingerprint', 'Face + Fingerprint'), ('face', 'Face Only'), ('fingerprint', 'Fingerprint Only'), ('manual', 'Manual Entry'), ('beacon', 'Beacon Auto Check-in')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fixed_early_departure_threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='fixed_end_time',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fixed_late_threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='fixed_start_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='working_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='employee',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fingerprint_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='random_verify_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='randomverification',
            name='face_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='early_departure_threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='late_threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
