# Generated by Django 5.2.3 on 2026-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_beacon_grace_period_company_lunch_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='require_face_with_beacon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='require_fingerprint_with_beacon',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_beacon_uuids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
