# Generated by Django 5.2.3 on 2026-06-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_company_require_face_with_beacon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_verification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_verification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_face_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_fingerprint_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BiometricAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_type', models.CharField(choices=[('face', 'Face'), ('fingerprint', 'Fingerprint')], max_length=20)),
                ('action', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('random_verification', 'Random Verification'), ('registration', 'Registration')], max_length=30)),
                ('success', models.BooleanField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_audits', to='users.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'biometric_type'], name='users_biome_employe_698bce_idx'), models.Index(fields=['timestamp'], name='users_biome_timesta_fde833_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=255)),
                ('finger_position', models.CharField(choices=[('RIGHT_THUMB', 'Right Thumb'), ('RIGHT_INDEX', 'Right Index'), ('RIGHT_MIDDLE', 'Right Middle'), ('RIGHT_RING', 'Right Ring'), ('RIGHT_PINKY', 'Right Pinky'), ('LEFT_THUMB', 'Left Thumb'), ('LEFT_INDEX', 'Left Index'), ('LEFT_MIDDLE', 'Left Middle'), ('LEFT_RING', 'Left Ring'), ('LEFT_PINKY', 'Left Pinky')], max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='users.employee')),
            ],
            options={
                'ordering': ['finger_position'],
                'unique_together': {('employee', 'finger_position')},
            },
        ),
    ]
