# Generated by Django 5.2.3 on 2026-06-30 20:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_face_failures_employee_face_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='office_beacon_uuids',
            field=models.JSONField(blank=True, default=users.models.Company.get_default_beacon),
        ),
    ]
